name: csOptimization

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  release-from-artifacts:
    needs: orchestrator-matrix
    runs-on: ubuntu-latest

    if: ${{ github.ref_type == 'tag' }}

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Show downloaded files
        run: find artifacts -type f

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            artifacts/**/*

  orchestrator-matrix:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - execution_id: 0
            os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            generator_cmake: Ninja
            runner: ubuntu-22.04
          - execution_id: 1
            os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            generator_cmake: Ninja Multi-Config
            runner: ubuntu-22.04
          - execution_id: 2
            os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            generator_cmake: Ninja
            runner: ubuntu-22.04
          - execution_id: 3
            os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            generator_cmake: Ninja Multi-Config
            runner: ubuntu-22.04
          - execution_id: 4
            os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            generator_cmake: Ninja
            runner: ubuntu-24.04
          - execution_id: 5
            os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            generator_cmake: Ninja Multi-Config
            runner: ubuntu-24.04
          - execution_id: 6
            os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            generator_cmake: Ninja
            runner: ubuntu-24.04
          - execution_id: 7
            os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            generator_cmake: Ninja Multi-Config
            runner: ubuntu-24.04
          - execution_id: 8
            os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvc
            compiler_version: default
            generator: msvc2022
            generator_type: multiconfig
            generator_cmake: Visual Studio 17 2022
            runner: windows-2022
          - execution_id: 9
            os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvc
            compiler_version: default
            generator: msvc2026
            generator_type: multiconfig
            generator_cmake: Visual Studio 18 2026
            runner: windows-2025-vs2026
          - execution_id: 10
            os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvcclang
            toolset: ClangCL
            compiler_version: default
            generator: msvc2022
            generator_type: multiconfig
            generator_cmake: Visual Studio 17 2022
            runner: windows-2022
          - execution_id: 11
            os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvcclang
            toolset: ClangCL
            compiler_version: default
            generator: msvc2026
            generator_type: multiconfig
            generator_cmake: Visual Studio 18 2026
            runner: windows-2025-vs2026

    steps:
      - name: csCMake Git clone/pull-ff
        uses: actions/checkout@v6
        with:
          repository: cscosine/csCMake.git
          path: workspace/csCMake
          ref: dev
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: csBlockMatrix Git clone/pull-ff
        uses: actions/checkout@v6
        with:
          repository: cscosine/csBlockMatrix.git
          path: workspace/csBlockMatrix
          ref: dev
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: csNelson Git clone/pull-ff
        uses: actions/checkout@v6
        with:
          repository: cscosine/csNelson.git
          path: workspace/csNelson
          ref: dev
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: Run command install apt packages
        if: ${{ matrix.os == 'linux' && startsWith(matrix.os_version, 'ubuntu') }}
        shell: bash
        run: |
          set -euo pipefail # enable strict mode


          packages=(
            libomp-dev
          )

          missing=()

          for pkg in "${packages[@]}"; do
            dpkg -s "$pkg" &>/dev/null || missing+=("$pkg")
          done

          if [ ${#missing[@]} -ne 0 ]; then

            sudo apt update

            echo "Need to install missing packages: ${missing[*]}"
            sudo apt install -y "${missing[@]}"
          else
            echo "All packages already installed."
          fi

      - name: Get Precompiled Lib eigen3 from 3rdPartyBaseLibs prepare filename
        id: filename_3rdPartyBaseLibs_eigen3
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_3rdPartyBaseLibs_eigen3=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-eigen3-3.4.0.tar.gz\n")

      - name: Get Precompiled Lib eigen3 from 3rdPartyBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/3rdPartyBaseLibs
          tag: v0.1.0-test
          fileName: ${{ steps.filename_3rdPartyBaseLibs_eigen3.outputs.filename_3rdPartyBaseLibs_eigen3 }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib eigen3 from 3rdPartyBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_eigen3.outputs.filename_3rdPartyBaseLibs_eigen3 }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_eigen3.outputs.filename_3rdPartyBaseLibs_eigen3 }}

      - name: Get Precompiled Lib cpptrace from 3rdPartyBaseLibs prepare filename
        id: filename_3rdPartyBaseLibs_cpptrace
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_3rdPartyBaseLibs_cpptrace=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-cpptrace-0.8.3.tar.gz\n")

      - name: Get Precompiled Lib cpptrace from 3rdPartyBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/3rdPartyBaseLibs
          tag: v0.1.0-test
          fileName: ${{ steps.filename_3rdPartyBaseLibs_cpptrace.outputs.filename_3rdPartyBaseLibs_cpptrace }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib cpptrace from 3rdPartyBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_cpptrace.outputs.filename_3rdPartyBaseLibs_cpptrace }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_cpptrace.outputs.filename_3rdPartyBaseLibs_cpptrace }}

      - name: Get Precompiled Lib magic_enum from 3rdPartyBaseLibs prepare filename
        id: filename_3rdPartyBaseLibs_magic_enum
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_3rdPartyBaseLibs_magic_enum=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-magic_enum-0.9.7.tar.gz\n")

      - name: Get Precompiled Lib magic_enum from 3rdPartyBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/3rdPartyBaseLibs
          tag: v0.1.0-test
          fileName: ${{ steps.filename_3rdPartyBaseLibs_magic_enum.outputs.filename_3rdPartyBaseLibs_magic_enum }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib magic_enum from 3rdPartyBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_magic_enum.outputs.filename_3rdPartyBaseLibs_magic_enum }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_magic_enum.outputs.filename_3rdPartyBaseLibs_magic_enum }}

      - name: Get Precompiled Lib libassert from 3rdPartyBaseLibs prepare filename
        id: filename_3rdPartyBaseLibs_libassert
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_3rdPartyBaseLibs_libassert=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-libassert-2.1.5.tar.gz\n")

      - name: Get Precompiled Lib libassert from 3rdPartyBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/3rdPartyBaseLibs
          tag: v0.1.0-test
          fileName: ${{ steps.filename_3rdPartyBaseLibs_libassert.outputs.filename_3rdPartyBaseLibs_libassert }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib libassert from 3rdPartyBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_libassert.outputs.filename_3rdPartyBaseLibs_libassert }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_libassert.outputs.filename_3rdPartyBaseLibs_libassert }}

      - name: Get Precompiled Lib Catch2 from 3rdPartyBaseLibs prepare filename
        id: filename_3rdPartyBaseLibs_Catch2
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_3rdPartyBaseLibs_Catch2=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-Catch2-3.10.0.tar.gz\n")

      - name: Get Precompiled Lib Catch2 from 3rdPartyBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/3rdPartyBaseLibs
          tag: v0.1.0-test
          fileName: ${{ steps.filename_3rdPartyBaseLibs_Catch2.outputs.filename_3rdPartyBaseLibs_Catch2 }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib Catch2 from 3rdPartyBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_Catch2.outputs.filename_3rdPartyBaseLibs_Catch2 }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_3rdPartyBaseLibs_Catch2.outputs.filename_3rdPartyBaseLibs_Catch2 }}

      - name: Get Precompiled Lib csCore from csBaseLibs prepare filename
        id: filename_csBaseLibs_csCore
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_csBaseLibs_csCore=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-csCore-1.0.0.tar.gz\n")

      - name: Get Precompiled Lib csCore from csBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/csBaseLibs
          tag: v0.1.0-rc1
          fileName: ${{ steps.filename_csBaseLibs_csCore.outputs.filename_csBaseLibs_csCore }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib csCore from csBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csCore.outputs.filename_csBaseLibs_csCore }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csCore.outputs.filename_csBaseLibs_csCore }}

      - name: Get Precompiled Lib csLie from csBaseLibs prepare filename
        id: filename_csBaseLibs_csLie
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_csBaseLibs_csLie=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-csLie-1.0.0.tar.gz\n")

      - name: Get Precompiled Lib csLie from csBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/csBaseLibs
          tag: v0.1.0-rc1
          fileName: ${{ steps.filename_csBaseLibs_csLie.outputs.filename_csBaseLibs_csLie }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib csLie from csBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csLie.outputs.filename_csBaseLibs_csLie }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csLie.outputs.filename_csBaseLibs_csLie }}

      - name: Get Precompiled Lib csCamera from csBaseLibs prepare filename
        id: filename_csBaseLibs_csCamera
        shell: python
        run: |
          import os

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"filename_csBaseLibs_csCamera=csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-csCamera-1.0.0.tar.gz\n")

      - name: Get Precompiled Lib csCamera from csBaseLibs download tar.gz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: cscosine/csBaseLibs
          tag: v0.1.0-rc1
          fileName: ${{ steps.filename_csBaseLibs_csCamera.outputs.filename_csBaseLibs_csCamera }}
          out-file-path: workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}

      - name: Get Precompiled Lib csCamera from csBaseLibs extract tar.gz
        shell: bash
        run: |
          tar -xzf workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csCamera.outputs.filename_csBaseLibs_csCamera }} -C workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          rm -f workspace/libs/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/${{ steps.filename_csBaseLibs_csCamera.outputs.filename_csBaseLibs_csCamera }}

      - name: cmake workflow on csBlockMatrix CMake Workflow for config(s) debug-release-relWithDebInfo-paranoid
        shell: bash
        run: |
          set -e
          if [[ "${{ matrix.generator_type }}" == "singleconfig" ]]; then
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-relWithDebInfo
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-paranoid
          elif [[ "${{ matrix.generator_type }}" == "multiconfig" ]]; then
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release-relWithDebInfo-paranoid
          else
            echo "Unknown generator_type: ${{ matrix.generator_type }}"
            exit 1
          fi
        working-directory: workspace/csBlockMatrix

      - name: cmake workflow on csNelson CMake Workflow for config(s) debug-release-relWithDebInfo-paranoid
        shell: bash
        run: |
          set -e
          if [[ "${{ matrix.generator_type }}" == "singleconfig" ]]; then
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-relWithDebInfo
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-paranoid
          elif [[ "${{ matrix.generator_type }}" == "multiconfig" ]]; then
            cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release-relWithDebInfo-paranoid
          else
            echo "Unknown generator_type: ${{ matrix.generator_type }}"
            exit 1
          fi
        working-directory: workspace/csNelson

      - name: Get Versions
        id: versions
        shell: python
        run: |
          from pathlib import Path
          import re
          import json
          import sys
          import os

          def grep_package_version(filename: Path) -> tuple[str | None, str | None]:
              path = Path(filename)

              if not path.is_file():
                  return (None, f"ERROR: file not found: {path}")

              content = path.read_text(encoding="utf-8")

              matches = []

              for m in re.finditer(
                  r'set\s*\(\s*PACKAGE_VERSION\s+("([^"]*)"|([^\s\)]+))\s*\)',
                  content,
              ):
                  value = m.group(2) or m.group(3)

                  # Ignore computed values like "${PACKAGE_VERSION} (...)"
                  if "${" in value:
                      continue

                  matches.append(value)

              if len(matches) != 1:
                  return (None, f"ERROR: {path}: expected exactly one PACKAGE_VERSION definition, found {len(matches)}")

              version = matches[0]
              return (version, None)

          def find_cmake_config_version(search_path: Path, name: str) -> tuple[Path | None, str | None]:
              candidates = {
                  f"{name}-config-version.cmake".lower(),
                  f"{name}ConfigVersion.cmake".lower(),
              }

              matches = [p for p in search_path.rglob("*") if p.is_file() and p.name.lower() in candidates]

              if not matches:
                  return (None, f"No config version file found for '{name}' under '{search_path}'")

              if len(matches) > 1:
                  return (None, "Multiple config version files found:" + ", ".join(str(p) for p in matches))

              return (matches[0], None)

          files = {
          }

          result = []


          for name, filename in files.items():
            v_or_err = grep_package_version(filename=filename)
            if v_or_err[0] is not None:
                version = v_or_err[0]
                result.append({'name': name,'version': version})
            elif v_or_err[1] is not None:
                sys.exit(f'ERROR: processing {name} at {filename}: {v_or_err[1]}')
            else:
                sys.exit('ERROR: unexpected behavior of grep_package_version processing {name} at {filename}')

          repos_auto_search_list = [
              "csBlockMatrix",
              "csNelson",
          ]

          for name in repos_auto_search_list:
            search_path: Path = Path('workspace/install/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}') / name
            path_or_err = find_cmake_config_version(search_path=search_path, name=name)
            if path_or_err[0] is not None:
              path = path_or_err[0]
              v_or_err = grep_package_version(filename=path)
              if v_or_err[0] is not None:
                version = v_or_err[0]
                result.append({'name': name,'version': version})
              elif v_or_err[1] is not None:
                sys.exit(f'ERROR: processing {name} at {path}: {v_or_err[1]}')
              else:
                sys.exit('ERROR: unexpected behavior of grep_package_version processing {name} at {path}')
            elif path_or_err[1] is not None:
                sys.exit(f'ERROR: processing {name} : {path_or_err[1]}')
            else:
                sys.exit('ERROR: unexpected behavior of find_cmake_config_version processing {name}')


          output_file = os.environ["GITHUB_OUTPUT"]
          with open(output_file, "w", encoding="utf-8") as f:
              f.write(f"packages={json.dumps(result)}\n")


      - name: Create Archives
        env:
          VERSIONS: ${{ steps.versions.outputs.packages }}
        shell: python
        run: |
          import json
          import os
          import tarfile
          from pathlib import Path

          versions = json.loads(os.environ['VERSIONS'])

          for entry in versions:
              name = entry['name']
              version = entry['version']
              install_subdir = Path('workspace/install/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}').resolve()
              input_path = Path(install_subdir / Path(name)).resolve()
              output_path = Path(install_subdir / Path('csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}' + '-' + name + '-' + version + '.tar.gz')).resolve()

              with tarfile.open(output_path, 'w:gz') as tar:
                  for path in input_path.rglob('*'):
                      resolved_path = path.resolve()
                      arcname = path.resolve().relative_to(install_subdir)
                      tar.add(resolved_path, arcname=arcname)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: csOptimization-0.1.0-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}
          path: workspace/install/csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}/*.tar.gz
